# "backend" dit au CMS de se connecter directement à GitHub
backend:
  name: github # <-- Correct
  repo: BlessEphraem/blessephraem.github.io 
  branch: main # Ou "master", selon votre branche
  site_domain: ephraem-blog.netlify.app
  
# "media_folder" est l'endroit où les images uploadées seront stockées
media_folder: "assets/uploads" 
public_folder: "/assets/uploads"

# "collections" (identique à avant)
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image de couverture", name: "thumbnail", widget: "image", required: false }
      - { label: "Contenu", name: "body", widget: "markdown" }